/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NaturalRouteImport } from './routes/natural'
import { Route as ScriptRouteImport } from './routes/script'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NaturalRoute = NaturalRouteImport.update({
  id: '/natural',
  path: '/natural',
  getParentRoute: () => rootRouteImport,
} as any)
const ScriptRoute = ScriptRouteImport.update({
  id: '/script',
  path: '/script',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/natural': typeof NaturalRoute
  '/script': typeof ScriptRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/natural': typeof NaturalRoute
  '/script': typeof ScriptRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/natural': typeof NaturalRoute
  '/script': typeof ScriptRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/natural' | '/script'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/natural' | '/script'
  id: '__root__' | '/' | '/natural' | '/script'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NaturalRoute: typeof NaturalRoute
  ScriptRoute: typeof ScriptRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/natural': {
      id: '/natural'
      path: '/natural'
      fullPath: '/natural'
      preLoaderRoute: typeof NaturalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/script': {
      id: '/script'
      path: '/script'
      fullPath: '/script'
      preLoaderRoute: typeof ScriptRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NaturalRoute: NaturalRoute,
  ScriptRoute: ScriptRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
